FROM mcr.microsoft.com/dotnet/sdk:8.0 AS test-env
WORKDIR /app

# Copy project files
COPY . ./

# Restore dependencies
RUN dotnet restore

# Run unit tests
ENTRYPOINT ["dotnet", "test", "--logger:trx"]
