// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "positive_emotion",
                            Text = "happy"
                        },
                        new
                        {
                            Id = 2,
                            Category = "positive_emotion",
                            Text = "joy"
                        },
                        new
                        {
                            Id = 3,
                            Category = "positive_emotion",
                            Text = "love"
                        },
                        new
                        {
                            Id = 4,
                            Category = "positive_emotion",
                            Text = "excited"
                        },
                        new
                        {
                            Id = 5,
                            Category = "positive_emotion",
                            Text = "content"
                        },
                        new
                        {
                            Id = 6,
                            Category = "positive_emotion",
                            Text = "pleased"
                        },
                        new
                        {
                            Id = 7,
                            Category = "positive_emotion",
                            Text = "grateful"
                        },
                        new
                        {
                            Id = 8,
                            Category = "positive_emotion",
                            Text = "hopeful"
                        },
                        new
                        {
                            Id = 9,
                            Category = "positive_emotion",
                            Text = "proud"
                        },
                        new
                        {
                            Id = 10,
                            Category = "positive_emotion",
                            Text = "amused"
                        },
                        new
                        {
                            Id = 11,
                            Category = "positive_emotion",
                            Text = "cheerful"
                        },
                        new
                        {
                            Id = 12,
                            Category = "positive_emotion",
                            Text = "delighted"
                        },
                        new
                        {
                            Id = 13,
                            Category = "positive_emotion",
                            Text = "optimistic"
                        },
                        new
                        {
                            Id = 14,
                            Category = "positive_emotion",
                            Text = "enthusiastic"
                        },
                        new
                        {
                            Id = 15,
                            Category = "positive_emotion",
                            Text = "satisfied"
                        },
                        new
                        {
                            Id = 16,
                            Category = "positive_emotion",
                            Text = "blissful"
                        },
                        new
                        {
                            Id = 17,
                            Category = "positive_emotion",
                            Text = "ecstatic"
                        },
                        new
                        {
                            Id = 18,
                            Category = "positive_emotion",
                            Text = "gleeful"
                        },
                        new
                        {
                            Id = 19,
                            Category = "positive_emotion",
                            Text = "jubilant"
                        },
                        new
                        {
                            Id = 20,
                            Category = "positive_emotion",
                            Text = "merry"
                        },
                        new
                        {
                            Id = 21,
                            Category = "positive_emotion",
                            Text = "radiant"
                        },
                        new
                        {
                            Id = 22,
                            Category = "positive_emotion",
                            Text = "thrilled"
                        },
                        new
                        {
                            Id = 23,
                            Category = "positive_emotion",
                            Text = "upbeat"
                        },
                        new
                        {
                            Id = 24,
                            Category = "positive_emotion",
                            Text = "vivacious"
                        },
                        new
                        {
                            Id = 25,
                            Category = "positive_emotion",
                            Text = "zestful"
                        },
                        new
                        {
                            Id = 26,
                            Category = "positive_emotion",
                            Text = "buoyant"
                        },
                        new
                        {
                            Id = 27,
                            Category = "positive_emotion",
                            Text = "elated"
                        },
                        new
                        {
                            Id = 28,
                            Category = "positive_emotion",
                            Text = "exhilarated"
                        },
                        new
                        {
                            Id = 29,
                            Category = "positive_emotion",
                            Text = "lighthearted"
                        },
                        new
                        {
                            Id = 30,
                            Category = "positive_emotion",
                            Text = "overjoyed"
                        },
                        new
                        {
                            Id = 31,
                            Category = "positive_emotion",
                            Text = "rapturous"
                        },
                        new
                        {
                            Id = 32,
                            Category = "positive_emotion",
                            Text = "triumphant"
                        },
                        new
                        {
                            Id = 33,
                            Category = "positive_emotion",
                            Text = "euphoric"
                        },
                        new
                        {
                            Id = 34,
                            Category = "positive_emotion",
                            Text = "exultant"
                        },
                        new
                        {
                            Id = 35,
                            Category = "positive_emotion",
                            Text = "festive"
                        },
                        new
                        {
                            Id = 36,
                            Category = "positive_emotion",
                            Text = "jolly"
                        },
                        new
                        {
                            Id = 37,
                            Category = "positive_emotion",
                            Text = "jovial"
                        },
                        new
                        {
                            Id = 38,
                            Category = "positive_emotion",
                            Text = "mirthful"
                        },
                        new
                        {
                            Id = 39,
                            Category = "positive_emotion",
                            Text = "peppy"
                        },
                        new
                        {
                            Id = 40,
                            Category = "positive_emotion",
                            Text = "perky"
                        },
                        new
                        {
                            Id = 41,
                            Category = "positive_emotion",
                            Text = "playful"
                        },
                        new
                        {
                            Id = 42,
                            Category = "positive_emotion",
                            Text = "sparkling"
                        },
                        new
                        {
                            Id = 43,
                            Category = "positive_emotion",
                            Text = "sunny"
                        },
                        new
                        {
                            Id = 44,
                            Category = "positive_emotion",
                            Text = "vibrant"
                        },
                        new
                        {
                            Id = 45,
                            Category = "positive_emotion",
                            Text = "whimsical"
                        },
                        new
                        {
                            Id = 46,
                            Category = "positive_emotion",
                            Text = "winsome"
                        },
                        new
                        {
                            Id = 47,
                            Category = "positive_emotion",
                            Text = "zany"
                        },
                        new
                        {
                            Id = 48,
                            Category = "positive_emotion",
                            Text = "carefree"
                        },
                        new
                        {
                            Id = 49,
                            Category = "positive_emotion",
                            Text = "ebullient"
                        },
                        new
                        {
                            Id = 50,
                            Category = "positive_emotion",
                            Text = "effervescent"
                        },
                        new
                        {
                            Id = 51,
                            Category = "positive_emotion",
                            Text = "exuberant"
                        },
                        new
                        {
                            Id = 52,
                            Category = "negative_emotion",
                            Text = "sad"
                        },
                        new
                        {
                            Id = 53,
                            Category = "negative_emotion",
                            Text = "angry"
                        },
                        new
                        {
                            Id = 54,
                            Category = "negative_emotion",
                            Text = "fear"
                        },
                        new
                        {
                            Id = 55,
                            Category = "negative_emotion",
                            Text = "anxious"
                        },
                        new
                        {
                            Id = 56,
                            Category = "negative_emotion",
                            Text = "depressed"
                        },
                        new
                        {
                            Id = 57,
                            Category = "negative_emotion",
                            Text = "frustrated"
                        },
                        new
                        {
                            Id = 58,
                            Category = "negative_emotion",
                            Text = "worried"
                        },
                        new
                        {
                            Id = 59,
                            Category = "negative_emotion",
                            Text = "upset"
                        },
                        new
                        {
                            Id = 60,
                            Category = "negative_emotion",
                            Text = "disappointed"
                        },
                        new
                        {
                            Id = 61,
                            Category = "negative_emotion",
                            Text = "guilty"
                        },
                        new
                        {
                            Id = 62,
                            Category = "negative_emotion",
                            Text = "ashamed"
                        },
                        new
                        {
                            Id = 63,
                            Category = "negative_emotion",
                            Text = "lonely"
                        },
                        new
                        {
                            Id = 64,
                            Category = "negative_emotion",
                            Text = "miserable"
                        },
                        new
                        {
                            Id = 65,
                            Category = "negative_emotion",
                            Text = "gloomy"
                        },
                        new
                        {
                            Id = 66,
                            Category = "negative_emotion",
                            Text = "desperate"
                        },
                        new
                        {
                            Id = 67,
                            Category = "negative_emotion",
                            Text = "hopeless"
                        },
                        new
                        {
                            Id = 68,
                            Category = "negative_emotion",
                            Text = "bitter"
                        },
                        new
                        {
                            Id = 69,
                            Category = "negative_emotion",
                            Text = "resentful"
                        },
                        new
                        {
                            Id = 70,
                            Category = "negative_emotion",
                            Text = "irritated"
                        },
                        new
                        {
                            Id = 71,
                            Category = "negative_emotion",
                            Text = "enraged"
                        },
                        new
                        {
                            Id = 72,
                            Category = "negative_emotion",
                            Text = "furious"
                        },
                        new
                        {
                            Id = 73,
                            Category = "negative_emotion",
                            Text = "aggravated"
                        },
                        new
                        {
                            Id = 74,
                            Category = "negative_emotion",
                            Text = "annoyed"
                        },
                        new
                        {
                            Id = 75,
                            Category = "negative_emotion",
                            Text = "disgruntled"
                        },
                        new
                        {
                            Id = 76,
                            Category = "negative_emotion",
                            Text = "displeased"
                        },
                        new
                        {
                            Id = 77,
                            Category = "negative_emotion",
                            Text = "exasperated"
                        },
                        new
                        {
                            Id = 78,
                            Category = "negative_emotion",
                            Text = "incensed"
                        },
                        new
                        {
                            Id = 79,
                            Category = "negative_emotion",
                            Text = "indignant"
                        },
                        new
                        {
                            Id = 80,
                            Category = "negative_emotion",
                            Text = "outraged"
                        },
                        new
                        {
                            Id = 81,
                            Category = "negative_emotion",
                            Text = "vexed"
                        },
                        new
                        {
                            Id = 82,
                            Category = "negative_emotion",
                            Text = "apprehensive"
                        },
                        new
                        {
                            Id = 83,
                            Category = "negative_emotion",
                            Text = "dreadful"
                        },
                        new
                        {
                            Id = 84,
                            Category = "negative_emotion",
                            Text = "frightened"
                        },
                        new
                        {
                            Id = 85,
                            Category = "negative_emotion",
                            Text = "panicked"
                        },
                        new
                        {
                            Id = 86,
                            Category = "negative_emotion",
                            Text = "petrified"
                        },
                        new
                        {
                            Id = 87,
                            Category = "negative_emotion",
                            Text = "terrified"
                        },
                        new
                        {
                            Id = 88,
                            Category = "negative_emotion",
                            Text = "alarmed"
                        },
                        new
                        {
                            Id = 89,
                            Category = "negative_emotion",
                            Text = "shocked"
                        },
                        new
                        {
                            Id = 90,
                            Category = "negative_emotion",
                            Text = "horrified"
                        },
                        new
                        {
                            Id = 91,
                            Category = "negative_emotion",
                            Text = "dismayed"
                        },
                        new
                        {
                            Id = 92,
                            Category = "negative_emotion",
                            Text = "distressed"
                        },
                        new
                        {
                            Id = 93,
                            Category = "negative_emotion",
                            Text = "grieved"
                        },
                        new
                        {
                            Id = 94,
                            Category = "negative_emotion",
                            Text = "heartbroken"
                        },
                        new
                        {
                            Id = 95,
                            Category = "negative_emotion",
                            Text = "melancholy"
                        },
                        new
                        {
                            Id = 96,
                            Category = "negative_emotion",
                            Text = "mournful"
                        },
                        new
                        {
                            Id = 97,
                            Category = "negative_emotion",
                            Text = "sorrowful"
                        },
                        new
                        {
                            Id = 98,
                            Category = "negative_emotion",
                            Text = "woeful"
                        },
                        new
                        {
                            Id = 99,
                            Category = "negative_emotion",
                            Text = "despondent"
                        },
                        new
                        {
                            Id = 100,
                            Category = "negative_emotion",
                            Text = "disheartened"
                        },
                        new
                        {
                            Id = 101,
                            Category = "negative_emotion",
                            Text = "forlorn"
                        },
                        new
                        {
                            Id = 102,
                            Category = "negative_emotion",
                            Text = "pessimistic"
                        },
                        new
                        {
                            Id = 103,
                            Category = "social",
                            Text = "friend"
                        },
                        new
                        {
                            Id = 104,
                            Category = "social",
                            Text = "family"
                        },
                        new
                        {
                            Id = 105,
                            Category = "social",
                            Text = "team"
                        },
                        new
                        {
                            Id = 106,
                            Category = "social",
                            Text = "community"
                        },
                        new
                        {
                            Id = 107,
                            Category = "social",
                            Text = "partner"
                        },
                        new
                        {
                            Id = 108,
                            Category = "social",
                            Text = "colleague"
                        },
                        new
                        {
                            Id = 109,
                            Category = "social",
                            Text = "neighbor"
                        },
                        new
                        {
                            Id = 110,
                            Category = "social",
                            Text = "acquaintance"
                        },
                        new
                        {
                            Id = 111,
                            Category = "social",
                            Text = "ally"
                        },
                        new
                        {
                            Id = 112,
                            Category = "social",
                            Text = "companion"
                        },
                        new
                        {
                            Id = 113,
                            Category = "social",
                            Text = "confidant"
                        },
                        new
                        {
                            Id = 114,
                            Category = "social",
                            Text = "mate"
                        },
                        new
                        {
                            Id = 115,
                            Category = "social",
                            Text = "peer"
                        },
                        new
                        {
                            Id = 116,
                            Category = "social",
                            Text = "supporter"
                        },
                        new
                        {
                            Id = 117,
                            Category = "social",
                            Text = "advocate"
                        },
                        new
                        {
                            Id = 118,
                            Category = "social",
                            Text = "backer"
                        },
                        new
                        {
                            Id = 119,
                            Category = "social",
                            Text = "benefactor"
                        },
                        new
                        {
                            Id = 120,
                            Category = "social",
                            Text = "comrade"
                        },
                        new
                        {
                            Id = 121,
                            Category = "social",
                            Text = "crony"
                        },
                        new
                        {
                            Id = 122,
                            Category = "social",
                            Text = "pal"
                        },
                        new
                        {
                            Id = 123,
                            Category = "social",
                            Text = "associate"
                        },
                        new
                        {
                            Id = 124,
                            Category = "social",
                            Text = "collaborator"
                        },
                        new
                        {
                            Id = 125,
                            Category = "social",
                            Text = "co-worker"
                        },
                        new
                        {
                            Id = 126,
                            Category = "social",
                            Text = "classmate"
                        },
                        new
                        {
                            Id = 127,
                            Category = "social",
                            Text = "roommate"
                        },
                        new
                        {
                            Id = 128,
                            Category = "social",
                            Text = "playmate"
                        },
                        new
                        {
                            Id = 129,
                            Category = "social",
                            Text = "soulmate"
                        },
                        new
                        {
                            Id = 130,
                            Category = "social",
                            Text = "spouse"
                        },
                        new
                        {
                            Id = 131,
                            Category = "social",
                            Text = "sibling"
                        },
                        new
                        {
                            Id = 132,
                            Category = "social",
                            Text = "parent"
                        },
                        new
                        {
                            Id = 133,
                            Category = "social",
                            Text = "child"
                        },
                        new
                        {
                            Id = 134,
                            Category = "social",
                            Text = "relative"
                        },
                        new
                        {
                            Id = 135,
                            Category = "social",
                            Text = "kin"
                        },
                        new
                        {
                            Id = 136,
                            Category = "social",
                            Text = "clan"
                        },
                        new
                        {
                            Id = 137,
                            Category = "social",
                            Text = "tribe"
                        },
                        new
                        {
                            Id = 138,
                            Category = "social",
                            Text = "group"
                        },
                        new
                        {
                            Id = 139,
                            Category = "social",
                            Text = "club"
                        },
                        new
                        {
                            Id = 140,
                            Category = "social",
                            Text = "society"
                        },
                        new
                        {
                            Id = 141,
                            Category = "social",
                            Text = "organization"
                        },
                        new
                        {
                            Id = 142,
                            Category = "social",
                            Text = "network"
                        },
                        new
                        {
                            Id = 143,
                            Category = "social",
                            Text = "circle"
                        },
                        new
                        {
                            Id = 144,
                            Category = "social",
                            Text = "crew"
                        },
                        new
                        {
                            Id = 145,
                            Category = "social",
                            Text = "gang"
                        },
                        new
                        {
                            Id = 146,
                            Category = "social",
                            Text = "posse"
                        },
                        new
                        {
                            Id = 147,
                            Category = "social",
                            Text = "squad"
                        },
                        new
                        {
                            Id = 148,
                            Category = "social",
                            Text = "unit"
                        },
                        new
                        {
                            Id = 149,
                            Category = "social",
                            Text = "band"
                        },
                        new
                        {
                            Id = 150,
                            Category = "social",
                            Text = "troop"
                        },
                        new
                        {
                            Id = 151,
                            Category = "social",
                            Text = "assembly"
                        },
                        new
                        {
                            Id = 152,
                            Category = "social",
                            Text = "congregation"
                        },
                        new
                        {
                            Id = 153,
                            Category = "social",
                            Text = "gathering"
                        },
                        new
                        {
                            Id = 154,
                            Category = "cognitive",
                            Text = "think"
                        },
                        new
                        {
                            Id = 155,
                            Category = "cognitive",
                            Text = "know"
                        },
                        new
                        {
                            Id = 156,
                            Category = "cognitive",
                            Text = "believe"
                        },
                        new
                        {
                            Id = 157,
                            Category = "cognitive",
                            Text = "understand"
                        },
                        new
                        {
                            Id = 158,
                            Category = "cognitive",
                            Text = "realize"
                        },
                        new
                        {
                            Id = 159,
                            Category = "cognitive",
                            Text = "consider"
                        },
                        new
                        {
                            Id = 160,
                            Category = "cognitive",
                            Text = "contemplate"
                        },
                        new
                        {
                            Id = 161,
                            Category = "cognitive",
                            Text = "ponder"
                        },
                        new
                        {
                            Id = 162,
                            Category = "cognitive",
                            Text = "reflect"
                        },
                        new
                        {
                            Id = 163,
                            Category = "cognitive",
                            Text = "analyze"
                        },
                        new
                        {
                            Id = 164,
                            Category = "cognitive",
                            Text = "evaluate"
                        },
                        new
                        {
                            Id = 165,
                            Category = "cognitive",
                            Text = "assess"
                        },
                        new
                        {
                            Id = 166,
                            Category = "cognitive",
                            Text = "judge"
                        },
                        new
                        {
                            Id = 167,
                            Category = "cognitive",
                            Text = "decide"
                        },
                        new
                        {
                            Id = 168,
                            Category = "cognitive",
                            Text = "conclude"
                        },
                        new
                        {
                            Id = 169,
                            Category = "cognitive",
                            Text = "deduce"
                        },
                        new
                        {
                            Id = 170,
                            Category = "cognitive",
                            Text = "infer"
                        },
                        new
                        {
                            Id = 171,
                            Category = "cognitive",
                            Text = "reason"
                        },
                        new
                        {
                            Id = 172,
                            Category = "cognitive",
                            Text = "rationalize"
                        },
                        new
                        {
                            Id = 173,
                            Category = "cognitive",
                            Text = "speculate"
                        },
                        new
                        {
                            Id = 174,
                            Category = "cognitive",
                            Text = "hypothesize"
                        },
                        new
                        {
                            Id = 175,
                            Category = "cognitive",
                            Text = "theorize"
                        },
                        new
                        {
                            Id = 176,
                            Category = "cognitive",
                            Text = "postulate"
                        },
                        new
                        {
                            Id = 177,
                            Category = "cognitive",
                            Text = "conjecture"
                        },
                        new
                        {
                            Id = 178,
                            Category = "cognitive",
                            Text = "surmise"
                        },
                        new
                        {
                            Id = 179,
                            Category = "cognitive",
                            Text = "guess"
                        },
                        new
                        {
                            Id = 180,
                            Category = "cognitive",
                            Text = "estimate"
                        },
                        new
                        {
                            Id = 181,
                            Category = "cognitive",
                            Text = "calculate"
                        },
                        new
                        {
                            Id = 182,
                            Category = "cognitive",
                            Text = "compute"
                        },
                        new
                        {
                            Id = 183,
                            Category = "cognitive",
                            Text = "measure"
                        },
                        new
                        {
                            Id = 184,
                            Category = "cognitive",
                            Text = "quantify"
                        },
                        new
                        {
                            Id = 185,
                            Category = "cognitive",
                            Text = "qualify"
                        },
                        new
                        {
                            Id = 186,
                            Category = "cognitive",
                            Text = "compare"
                        },
                        new
                        {
                            Id = 187,
                            Category = "cognitive",
                            Text = "contrast"
                        },
                        new
                        {
                            Id = 188,
                            Category = "cognitive",
                            Text = "differentiate"
                        },
                        new
                        {
                            Id = 189,
                            Category = "cognitive",
                            Text = "distinguish"
                        },
                        new
                        {
                            Id = 190,
                            Category = "cognitive",
                            Text = "identify"
                        },
                        new
                        {
                            Id = 191,
                            Category = "cognitive",
                            Text = "recognize"
                        },
                        new
                        {
                            Id = 192,
                            Category = "cognitive",
                            Text = "recall"
                        },
                        new
                        {
                            Id = 193,
                            Category = "cognitive",
                            Text = "remember"
                        },
                        new
                        {
                            Id = 194,
                            Category = "cognitive",
                            Text = "recollect"
                        },
                        new
                        {
                            Id = 195,
                            Category = "cognitive",
                            Text = "retrieve"
                        },
                        new
                        {
                            Id = 196,
                            Category = "cognitive",
                            Text = "forget"
                        },
                        new
                        {
                            Id = 197,
                            Category = "cognitive",
                            Text = "ignore"
                        },
                        new
                        {
                            Id = 198,
                            Category = "cognitive",
                            Text = "overlook"
                        },
                        new
                        {
                            Id = 199,
                            Category = "cognitive",
                            Text = "neglect"
                        },
                        new
                        {
                            Id = 200,
                            Category = "cognitive",
                            Text = "misunderstand"
                        },
                        new
                        {
                            Id = 201,
                            Category = "cognitive",
                            Text = "confuse"
                        },
                        new
                        {
                            Id = 202,
                            Category = "cognitive",
                            Text = "bewilder"
                        },
                        new
                        {
                            Id = 203,
                            Category = "cognitive",
                            Text = "perplex"
                        },
                        new
                        {
                            Id = 204,
                            Category = "cognitive",
                            Text = "puzzle"
                        });
                });

            modelBuilder.Entity("Core.Entities.JournalEntry", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany("JournalEntries")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("JournalEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
